const { neon } = require('@neondatabase/serverless');

const commandsData = {
  categories: [
    {
      slug: 'ai-chat',
      nameVi: 'AI & Trò chuyện',
      nameEn: 'AI & Chat',
      descriptionVi: 'Trò chuyện với Lena AI, phân tích hình ảnh, tìm kiếm web',
      descriptionEn: 'Chat with Lena AI, analyze images, web search',
      icon: 'faComments',
      color: 'text-blue-600',
      sortOrder: 1
    },
    {
      slug: 'games',
      nameVi: 'Trò chơi & Giải trí',
      nameEn: 'Games & Entertainment',
      descriptionVi: 'Trò chơi, GIF, hành động anime',
      descriptionEn: 'Games, GIFs, anime actions',
      icon: 'faGamepad',
      color: 'text-yellow-600',
      sortOrder: 2
    },
    {
      slug: 'giveaway',
      nameVi: 'Giveaway',
      nameEn: 'Giveaway',
      descriptionVi: 'Quản lý giveaway',
      descriptionEn: 'Manage giveaways',
      icon: 'faGift',
      color: 'text-green-600',
      sortOrder: 3
    },
    {
      slug: 'moderation',
      nameVi: 'Kiểm duyệt',
      nameEn: 'Moderation',
      descriptionVi: 'Ban, kick, mute, warn, purge',
      descriptionEn: 'Ban, kick, mute, warn, purge',
      icon: 'faShieldAlt',
      color: 'text-red-600',
      sortOrder: 4
    },
    {
      slug: 'utility',
      nameVi: 'Tiện ích',
      nameEn: 'Utility',
      descriptionVi: 'Ping, AFK, avatar, info, roll',
      descriptionEn: 'Ping, AFK, avatar, info, roll',
      icon: 'faWrench',
      color: 'text-purple-600',
      sortOrder: 5
    },
    {
      slug: 'admin',
      nameVi: 'Quản trị & Cấu hình',
      nameEn: 'Admin & Config',
      descriptionVi: 'Cấu hình bot, prefix, ngôn ngữ',
      descriptionEn: 'Bot config, prefix, language',
      icon: 'faTools',
      color: 'text-indigo-600',
      sortOrder: 6
    },
    {
      slug: 'automation',
      nameVi: 'Tự động hóa',
      nameEn: 'Automation & Moderation',
      descriptionVi: 'Auto moderation, auto roles, action logs',
      descriptionEn: 'Auto moderation, auto roles, action logs',
      icon: 'faShieldAlt',
      color: 'text-orange-600',
      sortOrder: 7
    }
  ],
  commands: [
    {
      categorySlug: 'ai-chat',
      name: '@Lena / lena',
      nameVi: '@Lena / lena',
      nameEn: '@Lena / lena',
      descriptionVi: 'Trò chuyện với Lena (6 tính cách)',
      descriptionEn: 'Chat with Lena (6 personalities)',
      usage: '@Lena <tin nhắn>',
      usageVi: '@Lena <tin nhắn>',
      usageEn: '@Lena <message>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 1
    },
    {
      categorySlug: 'ai-chat',
      name: '/analyze',
      nameVi: '/analyze',
      nameEn: '/analyze',
      descriptionVi: 'Phân tích hình ảnh với AI Vision',
      descriptionEn: 'Analyze images with AI Vision',
      usage: '/analyze image:<file> [question:<text>]',
      usageVi: '/analyze image:<tập tin> [question:<câu hỏi>]',
      usageEn: '/analyze image:<file> [question:<text>]',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 2
    },
    {
      categorySlug: 'ai-chat',
      name: 'search',
      nameVi: 'search',
      nameEn: 'search',
      descriptionVi: 'Tìm kiếm web với nguồn trích dẫn (Google + DuckDuckGo)',
      descriptionEn: 'Web search with citations (Google + DuckDuckGo)',
      usage: 'Tin nhắn: search <truy vấn>',
      usageVi: 'Tin nhắn: search <truy vấn>',
      usageEn: 'Message: search <query>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 3
    },
    {
      categorySlug: 'ai-chat',
      name: 'tutor',
      nameVi: 'tutor',
      nameEn: 'tutor',
      descriptionVi: 'Gia sư AI (lớp 1-12, Đại học, 10+ môn học)',
      descriptionEn: 'AI Tutor (grades 1-12, University, 10+ subjects)',
      usage: 'Tin nhắn: tutor <câu hỏi học tập>',
      usageVi: 'Tin nhắn: tutor <câu hỏi học tập>',
      usageEn: 'Message: tutor <study question>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 4
    },
    {
      categorySlug: 'ai-chat',
      name: 'code / debug',
      nameVi: 'code / debug',
      nameEn: 'code / debug',
      descriptionVi: 'Trợ lý lập trình (debug, review, học code)',
      descriptionEn: 'Code Assistant (debug, review, learn coding)',
      usage: 'Tin nhắn: code <vấn đề code>',
      usageVi: 'Tin nhắn: code <vấn đề code>',
      usageEn: 'Message: code <code issue>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 5
    },
    {
      categorySlug: 'ai-chat',
      name: 'news',
      nameVi: 'news',
      nameEn: 'news',
      descriptionVi: 'Tin tức mới nhất (Nhiều nguồn)',
      descriptionEn: 'Latest news (Multi-source)',
      usage: 'Tin nhắn: news [từ khóa]',
      usageVi: 'Tin nhắn: news [từ khóa]',
      usageEn: 'Message: news [keyword]',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 6
    },
    {
      categorySlug: 'ai-chat',
      name: 'game info',
      nameVi: 'game info',
      nameEn: 'game info',
      descriptionVi: 'Thông tin game (23 games: LoL, PUBG...)',
      descriptionEn: 'Game information (23 games: LoL, PUBG...)',
      usage: 'Tin nhắn: <tên game> <câu hỏi>',
      usageVi: 'Tin nhắn: <tên game> <câu hỏi>',
      usageEn: 'Message: <game name> <question>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 7
    },
    {
      categorySlug: 'ai-chat',
      name: 'confession',
      nameVi: 'confession',
      nameEn: 'confession',
      descriptionVi: 'Gửi confession ẩn danh',
      descriptionEn: 'Send anonymous confession',
      usage: 'DM: confession <nội dung>',
      usageVi: 'DM: confession <nội dung>',
      usageEn: 'DM: confession <content>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 8
    },
    {
      categorySlug: 'games',
      name: '/truthordare',
      nameVi: '/truthordare',
      nameEn: '/truthordare',
      descriptionVi: 'Truth or Dare',
      descriptionEn: 'Truth or Dare',
      usage: '/truthordare',
      usageVi: '/truthordare',
      usageEn: '/truthordare',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 1
    },
    {
      categorySlug: 'games',
      name: '/rps',
      nameVi: '/rps',
      nameEn: '/rps',
      descriptionVi: 'Kéo Búa Bao',
      descriptionEn: 'Rock Paper Scissors',
      usage: '/rps choice:<rock/paper/scissors>',
      usageVi: '/rps choice:<rock/paper/scissors>',
      usageEn: '/rps choice:<rock/paper/scissors>',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 2
    },
    {
      categorySlug: 'games',
      name: '/8ball',
      nameVi: '/8ball',
      nameEn: '/8ball',
      descriptionVi: 'Hỏi quả cầu ma thuật',
      descriptionEn: 'Ask the magic 8-ball',
      usage: '/8ball question:<câu hỏi>',
      usageVi: '/8ball question:<câu hỏi>',
      usageEn: '/8ball question:<question>',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 3
    },
    {
      categorySlug: 'games',
      name: '/gif',
      nameVi: '/gif',
      nameEn: '/gif',
      descriptionVi: 'Tìm GIF',
      descriptionEn: 'Search GIFs',
      usage: '/gif keyword:<từ khóa>',
      usageVi: '/gif keyword:<từ khóa>',
      usageEn: '/gif keyword:<keyword>',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 4
    },
    {
      categorySlug: 'games',
      name: '!hug / !kiss / !pat',
      nameVi: '!hug / !kiss / !pat',
      nameEn: '!hug / !kiss / !pat',
      descriptionVi: '70+ GIF hành động anime',
      descriptionEn: '70+ anime action GIFs',
      usage: '!<hành động> [@user]',
      usageVi: '!<hành động> [@user]',
      usageEn: '!<action> [@user]',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 5
    },
    {
      categorySlug: 'games',
      name: '!flip',
      nameVi: '!flip',
      nameEn: '!flip',
      descriptionVi: 'Tung đồng xu (Custom Lena emojis)',
      descriptionEn: 'Flip a coin (Custom Lena emojis)',
      usage: '!flip',
      usageVi: '!flip',
      usageEn: '!flip',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 6
    },
    {
      categorySlug: 'games',
      name: 'trivia',
      nameVi: 'trivia',
      nameEn: 'trivia',
      descriptionVi: 'Câu hỏi trắc nghiệm',
      descriptionEn: 'Trivia questions',
      usage: 'Tin nhắn: trivia',
      usageVi: 'Tin nhắn: trivia',
      usageEn: 'Message: trivia',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 7
    },
    {
      categorySlug: 'games',
      name: 'riddle',
      nameVi: 'riddle',
      nameEn: 'riddle',
      descriptionVi: 'Câu đố hại não',
      descriptionEn: 'Brain teasers',
      usage: 'Tin nhắn: riddle',
      usageVi: 'Tin nhắn: riddle',
      usageEn: 'Message: riddle',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 8
    },
    {
      categorySlug: 'games',
      name: 'word game',
      nameVi: 'word game',
      nameEn: 'word game',
      descriptionVi: 'Trò chơi đoán từ',
      descriptionEn: 'Word guessing game',
      usage: 'Tin nhắn: word game',
      usageVi: 'Tin nhắn: word game',
      usageEn: 'Message: word game',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 9
    },
    {
      categorySlug: 'giveaway',
      name: '/giveaway create',
      nameVi: '/giveaway create',
      nameEn: '/giveaway create',
      descriptionVi: 'Tạo giveaway',
      descriptionEn: 'Create giveaway',
      usage: '/giveaway create duration:<1h> prize:<giải thưởng>',
      usageVi: '/giveaway create duration:<1h> prize:<giải thưởng>',
      usageEn: '/giveaway create duration:<1h> prize:<prize>',
      aliases: ['!lga create'],
      isSlashCommand: true,
      sortOrder: 1
    },
    {
      categorySlug: 'giveaway',
      name: '/giveaway end',
      nameVi: '/giveaway end',
      nameEn: '/giveaway end',
      descriptionVi: 'Kết thúc giveaway',
      descriptionEn: 'End giveaway',
      usage: '/giveaway end giveaway_id:<id>',
      usageVi: '/giveaway end giveaway_id:<id>',
      usageEn: '/giveaway end giveaway_id:<id>',
      aliases: ['!lga end'],
      isSlashCommand: true,
      sortOrder: 2
    },
    {
      categorySlug: 'giveaway',
      name: '/giveaway reroll',
      nameVi: '/giveaway reroll',
      nameEn: '/giveaway reroll',
      descriptionVi: 'Quay lại người thắng',
      descriptionEn: 'Reroll winner',
      usage: '/giveaway reroll giveaway_id:<id>',
      usageVi: '/giveaway reroll giveaway_id:<id>',
      usageEn: '/giveaway reroll giveaway_id:<id>',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 3
    },
    {
      categorySlug: 'giveaway',
      name: '/giveaway list',
      nameVi: '/giveaway list',
      nameEn: '/giveaway list',
      descriptionVi: 'Xem giveaway đang chạy',
      descriptionEn: 'View active giveaways',
      usage: '/giveaway list',
      usageVi: '/giveaway list',
      usageEn: '/giveaway list',
      aliases: [],
      isSlashCommand: true,
      sortOrder: 4
    },
    {
      categorySlug: 'moderation',
      name: '/ban',
      nameVi: '/ban',
      nameEn: '/ban',
      descriptionVi: 'Ban người dùng',
      descriptionEn: 'Ban user',
      usage: '/ban user:<@user> [reason:<lý do>]',
      usageVi: '/ban user:<@user> [reason:<lý do>]',
      usageEn: '/ban user:<@user> [reason:<reason>]',
      aliases: [],
      isSlashCommand: true,
      permissions: 'BAN_MEMBERS',
      sortOrder: 1
    },
    {
      categorySlug: 'moderation',
      name: '/kick',
      nameVi: '/kick',
      nameEn: '/kick',
      descriptionVi: 'Kick người dùng',
      descriptionEn: 'Kick user',
      usage: '/kick user:<@user> [reason:<lý do>]',
      usageVi: '/kick user:<@user> [reason:<lý do>]',
      usageEn: '/kick user:<@user> [reason:<reason>]',
      aliases: [],
      isSlashCommand: true,
      permissions: 'KICK_MEMBERS',
      sortOrder: 2
    },
    {
      categorySlug: 'moderation',
      name: '/mute',
      nameVi: '/mute',
      nameEn: '/mute',
      descriptionVi: 'Mute người dùng',
      descriptionEn: 'Mute user',
      usage: '/mute user:<@user> duration:<phút> [reason]',
      usageVi: '/mute user:<@user> duration:<phút> [reason]',
      usageEn: '/mute user:<@user> duration:<minutes> [reason]',
      aliases: [],
      isSlashCommand: true,
      permissions: 'MODERATE_MEMBERS',
      sortOrder: 3
    },
    {
      categorySlug: 'moderation',
      name: '/warn',
      nameVi: '/warn',
      nameEn: '/warn',
      descriptionVi: 'Cảnh báo người dùng',
      descriptionEn: 'Warn user',
      usage: '/warn user:<@user> [reason:<lý do>]',
      usageVi: '/warn user:<@user> [reason:<lý do>]',
      usageEn: '/warn user:<@user> [reason:<reason>]',
      aliases: [],
      isSlashCommand: true,
      permissions: 'MODERATE_MEMBERS',
      sortOrder: 4
    },
    {
      categorySlug: 'moderation',
      name: '!purge',
      nameVi: '!purge',
      nameEn: '!purge',
      descriptionVi: 'Xóa tin nhắn',
      descriptionEn: 'Delete messages',
      usage: '!purge <số lượng>',
      usageVi: '!purge <số lượng>',
      usageEn: '!purge <number>',
      aliases: [],
      isSlashCommand: false,
      permissions: 'MANAGE_MESSAGES',
      sortOrder: 5
    },
    {
      categorySlug: 'utility',
      name: '!ping',
      nameVi: '!ping',
      nameEn: '!ping',
      descriptionVi: 'Kiểm tra ping bot',
      descriptionEn: 'Check bot ping',
      usage: '!ping',
      usageVi: '!ping',
      usageEn: '!ping',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 1
    },
    {
      categorySlug: 'utility',
      name: '!afk',
      nameVi: '!afk',
      nameEn: '!afk',
      descriptionVi: 'Đặt trạng thái AFK',
      descriptionEn: 'Set AFK status',
      usage: '!afk [lý do]',
      usageVi: '!afk [lý do]',
      usageEn: '!afk [reason]',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 2
    },
    {
      categorySlug: 'utility',
      name: '!avatar',
      nameVi: '!avatar',
      nameEn: '!avatar',
      descriptionVi: 'Xem avatar người dùng',
      descriptionEn: 'View user avatar',
      usage: '!avatar [@user]',
      usageVi: '!avatar [@user]',
      usageEn: '!avatar [@user]',
      aliases: ['!av'],
      isSlashCommand: false,
      sortOrder: 3
    },
    {
      categorySlug: 'utility',
      name: '!banner',
      nameVi: '!banner',
      nameEn: '!banner',
      descriptionVi: 'Xem banner người dùng',
      descriptionEn: 'View user banner',
      usage: '!banner [@user]',
      usageVi: '!banner [@user]',
      usageEn: '!banner [@user]',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 4
    },
    {
      categorySlug: 'utility',
      name: '!serverinfo',
      nameVi: '!serverinfo',
      nameEn: '!serverinfo',
      descriptionVi: 'Thông tin server chi tiết',
      descriptionEn: 'Detailed server info',
      usage: '!serverinfo',
      usageVi: '!serverinfo',
      usageEn: '!serverinfo',
      aliases: ['!si'],
      isSlashCommand: false,
      sortOrder: 5
    },
    {
      categorySlug: 'utility',
      name: '!botinfo',
      nameVi: '!botinfo',
      nameEn: '!botinfo',
      descriptionVi: 'Thông tin Lena Bot (format đẹp mới)',
      descriptionEn: 'Lena Bot information (new beautiful format)',
      usage: '!botinfo / !info',
      usageVi: '!botinfo / !info',
      usageEn: '!botinfo / !info',
      aliases: ['!info'],
      isSlashCommand: false,
      sortOrder: 6
    },
    {
      categorySlug: 'utility',
      name: '!uptime',
      nameVi: '!uptime',
      nameEn: '!uptime',
      descriptionVi: 'Thời gian bot hoạt động',
      descriptionEn: 'Bot uptime',
      usage: '!uptime',
      usageVi: '!uptime',
      usageEn: '!uptime',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 7
    },
    {
      categorySlug: 'utility',
      name: '!roll',
      nameVi: '!roll',
      nameEn: '!roll',
      descriptionVi: 'Tung xúc xắc',
      descriptionEn: 'Roll dice',
      usage: '!roll [số]d[mặt]',
      usageVi: '!roll [số]d[mặt]',
      usageEn: '!roll [number]d[sides]',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 8
    },
    {
      categorySlug: 'utility',
      name: '!whois',
      nameVi: '!whois',
      nameEn: '!whois',
      descriptionVi: 'Xem thông tin chi tiết người dùng',
      descriptionEn: 'View detailed user info',
      usage: '!whois [@user/id]',
      usageVi: '!whois [@user/id]',
      usageEn: '!whois [@user/id]',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 9
    },
    {
      categorySlug: 'utility',
      name: '!membercount',
      nameVi: '!membercount',
      nameEn: '!membercount',
      descriptionVi: 'Đếm số thành viên server',
      descriptionEn: 'Count server members',
      usage: '!membercount',
      usageVi: '!membercount',
      usageEn: '!membercount',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 10
    },
    {
      categorySlug: 'utility',
      name: '!randomcolor',
      nameVi: '!randomcolor',
      nameEn: '!randomcolor',
      descriptionVi: 'Màu ngẫu nhiên với xem trước',
      descriptionEn: 'Random color with preview',
      usage: '!randomcolor',
      usageVi: '!randomcolor',
      usageEn: '!randomcolor',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 11
    },
    {
      categorySlug: 'utility',
      name: '!cat / !dog / !pug',
      nameVi: '!cat / !dog / !pug',
      nameEn: '!cat / !dog / !pug',
      descriptionVi: 'Ảnh động vật ngẫu nhiên',
      descriptionEn: 'Random animal images',
      usage: '!cat / !dog / !pug',
      usageVi: '!cat / !dog / !pug',
      usageEn: '!cat / !dog / !pug',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 12
    },
    {
      categorySlug: 'utility',
      name: '!pokemon',
      nameVi: '!pokemon',
      nameEn: '!pokemon',
      descriptionVi: 'Thông tin Pokemon từ PokeAPI',
      descriptionEn: 'Pokemon info from PokeAPI',
      usage: '!pokemon <tên>',
      usageVi: '!pokemon <tên>',
      usageEn: '!pokemon <name>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 13
    },
    {
      categorySlug: 'utility',
      name: '!itunes',
      nameVi: '!itunes',
      nameEn: '!itunes',
      descriptionVi: 'Tìm bài hát iTunes',
      descriptionEn: 'Search iTunes songs',
      usage: '!itunes <bài hát>',
      usageVi: '!itunes <bài hát>',
      usageEn: '!itunes <song>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 14
    },
    {
      categorySlug: 'utility',
      name: '!poll',
      nameVi: '!poll',
      nameEn: '!poll',
      descriptionVi: 'Tạo bình chọn với reactions (tối đa 10)',
      descriptionEn: 'Create poll with reactions (max 10)',
      usage: '!poll "Câu hỏi" "Lựa chọn1" "Lựa chọn2"',
      usageVi: '!poll "Câu hỏi" "Lựa chọn1" "Lựa chọn2"',
      usageEn: '!poll "Question" "Choice1" "Choice2"',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 15
    },
    {
      categorySlug: 'utility',
      name: '!github',
      nameVi: '!github',
      nameEn: '!github',
      descriptionVi: 'Thông tin GitHub repo',
      descriptionEn: 'GitHub repo info',
      usage: '!github <owner/repo>',
      usageVi: '!github <owner/repo>',
      usageEn: '!github <owner/repo>',
      aliases: [],
      isSlashCommand: false,
      sortOrder: 16
    },
    {
      categorySlug: 'admin',
      name: '/setmode',
      nameVi: '/setmode',
      nameEn: '/setmode',
      descriptionVi: 'Đổi chế độ tính cách',
      descriptionEn: 'Change personality mode',
      usage: '/setmode mode:<lena/support/technical...>',
      usageVi: '/setmode mode:<lena/support/technical...>',
      usageEn: '/setmode mode:<lena/support/technical...>',
      aliases: [],
      isSlashCommand: true,
      permissions: 'ADMINISTRATOR',
      sortOrder: 1
    },
    {
      categorySlug: 'admin',
      name: '!setprefix',
      nameVi: '!setprefix',
      nameEn: '!setprefix',
      descriptionVi: 'Đổi prefix lệnh',
      descriptionEn: 'Change command prefix',
      usage: '!setprefix <prefix>',
      usageVi: '!setprefix <prefix>',
      usageEn: '!setprefix <prefix>',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 2
    },
    {
      categorySlug: 'admin',
      name: '!setlang',
      nameVi: '!setlang',
      nameEn: '!setlang',
      descriptionVi: 'Đổi ngôn ngữ server (vi/en)',
      descriptionEn: 'Change server language (vi/en)',
      usage: '!setlang <vi|en>',
      usageVi: '!setlang <vi|en>',
      usageEn: '!setlang <vi|en>',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 3
    },
    {
      categorySlug: 'admin',
      name: '/config',
      nameVi: '/config',
      nameEn: '/config',
      descriptionVi: 'Xem cấu hình server',
      descriptionEn: 'View server config',
      usage: '/config',
      usageVi: '/config',
      usageEn: '/config',
      aliases: ['!conf'],
      isSlashCommand: true,
      permissions: 'ADMINISTRATOR',
      sortOrder: 4
    },
    {
      categorySlug: 'admin',
      name: '/embed',
      nameVi: '/embed',
      nameEn: '/embed',
      descriptionVi: 'Quản lý embed tùy chỉnh',
      descriptionEn: 'Manage custom embeds',
      usage: '/embed <create/delete/list...>',
      usageVi: '/embed <create/delete/list...>',
      usageEn: '/embed <create/delete/list...>',
      aliases: ['!emb'],
      isSlashCommand: true,
      permissions: 'ADMINISTRATOR',
      sortOrder: 5
    },
    {
      categorySlug: 'admin',
      name: '/response',
      nameVi: '/response',
      nameEn: '/response',
      descriptionVi: 'Tự động trả lời tùy chỉnh',
      descriptionEn: 'Custom auto-responses',
      usage: '/response <add/list/delete>',
      usageVi: '/response <add/list/delete>',
      usageEn: '/response <add/list/delete>',
      aliases: ['!resp'],
      isSlashCommand: true,
      permissions: 'ADMINISTRATOR',
      sortOrder: 6
    },
    {
      categorySlug: 'admin',
      name: '!blacklist',
      nameVi: '!blacklist',
      nameEn: '!blacklist',
      descriptionVi: 'Quản lý bộ lọc 18+',
      descriptionEn: 'Manage 18+ filter',
      usage: '!blacklist <add/remove/list>',
      usageVi: '!blacklist <add/remove/list>',
      usageEn: '!blacklist <add/remove/list>',
      aliases: ['!bl'],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 7
    },
    {
      categorySlug: 'automation',
      name: '!automod',
      nameVi: '!automod',
      nameEn: '!automod',
      descriptionVi: 'Tự động kiểm duyệt (spam, links, caps, mentions)',
      descriptionEn: 'Auto moderation (spam, links, caps, mentions)',
      usage: '!automod <enable|disable|config>',
      usageVi: '!automod <enable|disable|config>',
      usageEn: '!automod <enable|disable|config>',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 1
    },
    {
      categorySlug: 'automation',
      name: '!actionlogs',
      nameVi: '!actionlogs',
      nameEn: '!actionlogs',
      descriptionVi: 'Log sự kiện member/message vào kênh',
      descriptionEn: 'Log member/message events to channel',
      usage: '!actionlogs <enable|disable> [#channel]',
      usageVi: '!actionlogs <enable|disable> [#channel]',
      usageEn: '!actionlogs <enable|disable> [#channel]',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 2
    },
    {
      categorySlug: 'automation',
      name: '!autodelete',
      nameVi: '!autodelete',
      nameEn: '!autodelete',
      descriptionVi: 'Tự động xóa tin nhắn sau X giây',
      descriptionEn: 'Auto delete messages after X seconds',
      usage: '!autodelete <enable|disable> #channel <giây>',
      usageVi: '!autodelete <enable|disable> #channel <giây>',
      usageEn: '!autodelete <enable|disable> #channel <seconds>',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 3
    },
    {
      categorySlug: 'automation',
      name: '!autoroles',
      nameVi: '!autoroles',
      nameEn: '!autoroles',
      descriptionVi: 'Tự động gán role khi thành viên join',
      descriptionEn: 'Auto assign roles when member joins',
      usage: '!autoroles <enable|disable|add|remove> [role]',
      usageVi: '!autoroles <enable|disable|add|remove> [role]',
      usageEn: '!autoroles <enable|disable|add|remove> [role]',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      sortOrder: 4
    },
    {
      categorySlug: 'automation',
      name: '!customcmd',
      nameVi: '!customcmd',
      nameEn: '!customcmd',
      descriptionVi: 'Lệnh tùy chỉnh với biến (Premium)',
      descriptionEn: 'Custom commands with variables (Premium)',
      usage: '!customcmd <create|delete|list> [name]',
      usageVi: '!customcmd <create|delete|list> [name]',
      usageEn: '!customcmd <create|delete|list> [name]',
      aliases: [],
      isSlashCommand: false,
      permissions: 'ADMINISTRATOR',
      isPremium: true,
      sortOrder: 5
    }
  ]
};

async function syncCommandsToDatabase() {
  if (!process.env.DATABASE_URL) {
    console.log('❌ DATABASE_URL not found, skipping command sync');
    return;
  }

  const sql = neon(process.env.DATABASE_URL);

  try {
    console.log('🔄 Starting command sync...');

    await sql`DELETE FROM bot_command_categories`;
    console.log('✅ Cleared old categories');

    for (const category of commandsData.categories) {
      await sql`
        INSERT INTO bot_command_categories (slug, name_vi, name_en, description_vi, description_en, icon, color, sort_order, last_synced_at)
        VALUES (${category.slug}, ${category.nameVi}, ${category.nameEn}, ${category.descriptionVi || ''}, ${category.descriptionEn || ''}, ${category.icon}, ${category.color}, ${category.sortOrder}, NOW())
      `;
    }
    console.log(`✅ Synced ${commandsData.categories.length} categories`);

    await sql`DELETE FROM bot_commands`;
    console.log('✅ Cleared old commands');

    for (const cmd of commandsData.commands) {
      await sql`
        INSERT INTO bot_commands (
          category_slug, name, name_vi, name_en, description_vi, description_en, 
          usage, usage_vi, usage_en, aliases, permissions, is_premium, is_slash_command, sort_order, last_synced_at
        )
        VALUES (
          ${cmd.categorySlug}, ${cmd.name}, ${cmd.nameVi || cmd.name}, ${cmd.nameEn || cmd.name}, 
          ${cmd.descriptionVi}, ${cmd.descriptionEn}, ${cmd.usage}, 
          ${cmd.usageVi || cmd.usage}, ${cmd.usageEn || cmd.usage}, 
          ${JSON.stringify(cmd.aliases || [])}, ${cmd.permissions || null}, 
          ${cmd.isPremium || false}, ${cmd.isSlashCommand || false}, ${cmd.sortOrder}, NOW()
        )
      `;
    }
    console.log(`✅ Synced ${commandsData.commands.length} commands`);

    console.log('✨ Command sync completed successfully!');
  } catch (error) {
    console.error('❌ Error syncing commands:', error);
  }
}

module.exports = { syncCommandsToDatabase };
